<template>
  <section class="profile-page">
    <div class="page-heading"><div><p class="eyebrow">ApplyMate</p><h1>个人档案</h1><p>简历解析与浏览器填写的信息源；保存时自动创建版本快照。</p></div><div class="profile-actions"><el-tag type="info">Schema {{ profile.schemaVersion }}</el-tag><el-tag type="success">修订 {{ profile.revision }}</el-tag><el-button :loading="loading" @click="load">刷新</el-button><el-button v-if="!editing" type="primary" @click="editing = true">编辑档案</el-button><el-button v-else @click="cancelEdit">取消</el-button><el-button v-if="editing" type="primary" :loading="saving" @click="save">保存档案</el-button></div></div>
    <el-alert :title="serviceOnline ? `当前已连接：${runtimeLabel}。档案、快照与扩展配对均保存在该端；Web(MySQL) 与桌面端(H2) 默认不同步。` : '本地 JobTracker 服务未连接：请启动后端或桌面端。'" :type="serviceOnline ? 'success' : 'warning'" :closable="false" show-icon />
    <el-form :disabled="!editing" label-position="left" label-width="76px" size="small" class="profile-form">
      <el-card class="form-card"><template #header><div class="card-header"><span>基本信息</span><small>通用填写字段</small></div></template><div class="compact-grid three"><el-form-item label="中文姓名"><el-input v-model="form.basic.nameCn" placeholder="姓名" /></el-form-item><el-form-item label="性别"><el-select v-model="form.basic.gender"><el-option label="未填写" value="UNSPECIFIED" /><el-option label="男" value="MALE" /><el-option label="女" value="FEMALE" /></el-select></el-form-item><el-form-item label="当前城市"><el-input v-model="form.contact.currentCity" placeholder="杭州" /></el-form-item><el-form-item label="邮箱"><el-input v-model="form.contact.email" placeholder="name@example.com" /></el-form-item><el-form-item label="手机号码"><el-input v-model="form.contact.phone" placeholder="手机号" /></el-form-item></div></el-card>
      <el-card class="form-card"><template #header><SectionHeader title="教育经历" hint="扩展默认使用第一条" :editable="editing" @add="addEducation" /></template><el-empty v-if="!form.education.length" description="尚未添加教育经历" :image-size="48"><el-button size="small" type="primary" plain :disabled="!editing" @click="addEducation">添加教育经历</el-button></el-empty><ExperienceBlock v-for="(item,index) in form.education" :key="item.id" :title="`教育经历 ${index + 1}`" :editable="editing" :summary="[item.school, item.degree, item.major].filter(Boolean).join(' · ') || '信息未填写'" @remove="removeEducation(index)"><div class="compact-grid four"><el-form-item label="学校名称" required><el-input v-model="item.school" /></el-form-item><el-form-item label="学历"><el-select v-model="item.degree"><el-option label="本科" value="BACHELOR" /><el-option label="硕士" value="MASTER" /><el-option label="博士" value="DOCTOR" /></el-select></el-form-item><el-form-item label="专业"><el-input v-model="item.major" /></el-form-item><el-form-item label="学院"><el-input v-model="item.college" /></el-form-item><el-form-item label="入学时间"><el-input v-model="item.startDate" placeholder="YYYY-MM" /></el-form-item><el-form-item label="毕业时间"><el-input v-model="item.expectedGraduation" placeholder="YYYY-MM" /></el-form-item><el-form-item label="学历形式"><el-select v-model="item.studyMode"><el-option label="全日制" value="FULL_TIME" /><el-option label="非全日制" value="PART_TIME" /></el-select></el-form-item><el-form-item label="GPA / 排名"><el-input v-model="item.gpa" placeholder="3.8 / 10%" /></el-form-item></div></ExperienceBlock></el-card>
      <el-card class="form-card"><template #header><SectionHeader title="实习经历" hint="支持多条，按时间倒序填写" @add="addInternship" /></template><el-empty v-if="!form.work.length" description="尚未添加实习经历" :image-size="48"><el-button size="small" type="primary" plain @click="addInternship">添加实习经历</el-button></el-empty><ExperienceBlock v-for="(item,index) in form.work" :key="item.id" :title="item.company || `实习经历 ${index + 1}`" @remove="removeInternship(index)"><div class="compact-grid four"><el-form-item label="公司名称" required><el-input v-model="item.company" placeholder="公司" /></el-form-item><el-form-item label="实习岗位"><el-input v-model="item.role" placeholder="岗位" /></el-form-item><el-form-item label="所属部门"><el-input v-model="item.department" /></el-form-item><el-form-item label="工作城市"><el-input v-model="item.city" /></el-form-item><el-form-item label="开始时间"><el-input v-model="item.startDate" placeholder="YYYY-MM" /></el-form-item><el-form-item label="结束时间"><el-input v-model="item.endDate" placeholder="YYYY-MM" /></el-form-item><el-form-item label="工作类型"><el-select v-model="item.employmentType"><el-option label="实习" value="INTERNSHIP" /><el-option label="全职" value="FULL_TIME" /><el-option label="兼职" value="PART_TIME" /></el-select></el-form-item><el-form-item label="行业"><el-input v-model="item.industry" /></el-form-item></div><div class="detail-grid"><el-form-item label="工作职责"><el-input v-model="item.responsibilities" type="textarea" :rows="2" placeholder="负责的工作、协作对象与范围" /></el-form-item><el-form-item label="成果与量化"><el-input v-model="item.achievements" type="textarea" :rows="2" placeholder="结果、指标、奖项或业务影响" /></el-form-item><el-form-item label="技术/工具"><el-input v-model="item.technologies" placeholder="例如：Java、Spring Boot、MySQL" /></el-form-item></div></ExperienceBlock></el-card>
      <el-card class="form-card"><template #header><SectionHeader title="项目经历" hint="支持多条，可用于项目类申请表" @add="addProject" /></template><el-empty v-if="!form.projects.length" description="尚未添加项目经历" :image-size="48"><el-button size="small" type="primary" plain @click="addProject">添加项目经历</el-button></el-empty><ExperienceBlock v-for="(item,index) in form.projects" :key="item.id" :title="item.name || `项目经历 ${index + 1}`" @remove="removeProject(index)"><div class="compact-grid four"><el-form-item label="项目名称" required><el-input v-model="item.name" /></el-form-item><el-form-item label="担任角色"><el-input v-model="item.role" /></el-form-item><el-form-item label="开始时间"><el-input v-model="item.startDate" placeholder="YYYY-MM" /></el-form-item><el-form-item label="结束时间"><el-input v-model="item.endDate" placeholder="YYYY-MM" /></el-form-item><el-form-item label="项目类型"><el-input v-model="item.type" placeholder="课程 / 个人 / 商业" /></el-form-item><el-form-item label="团队规模"><el-input v-model="item.teamSize" placeholder="例如：5 人" /></el-form-item><el-form-item label="项目链接"><el-input v-model="item.url" placeholder="GitHub、Demo 或作品集" /></el-form-item><el-form-item label="技术栈"><el-input v-model="item.technologies" placeholder="技术、框架、工具" /></el-form-item></div><div class="detail-grid"><el-form-item label="项目简介"><el-input v-model="item.description" type="textarea" :rows="2" placeholder="背景、目标与核心功能" /></el-form-item><el-form-item label="个人贡献"><el-input v-model="item.contributions" type="textarea" :rows="2" placeholder="你的负责内容、难点与成果" /></el-form-item></div></ExperienceBlock></el-card>
    </el-form>
    <el-card class="snapshot-card"><template #header><div class="card-header"><span>版本快照</span><small>恢复会生成新的修订记录</small></div></template><el-empty v-if="!snapshots.length" description="尚未保存档案快照" :image-size="56" /><el-table v-else :data="snapshots" size="small"><el-table-column prop="revision" label="修订" width="90"><template #default="{ row }">v{{ row.revision }}</template></el-table-column><el-table-column prop="createdAt" label="保存时间" min-width="180" /><el-table-column label="操作" width="100"><template #default="{ row }"><el-button text type="primary" @click="restore(row)">恢复</el-button></template></el-table-column></el-table></el-card>
    <el-card class="pairing-card"><template #header><div class="card-header"><span>浏览器扩展配对</span><small>仅批准你刚在 Chrome 中发起的请求</small></div></template><el-empty v-if="!pairingRequests.length" description="没有待批准的扩展请求" :image-size="56" /><el-table v-else :data="pairingRequests" size="small"><el-table-column prop="displayName" label="扩展" min-width="160" /><el-table-column prop="extensionId" label="Extension ID" min-width="240" show-overflow-tooltip /><el-table-column prop="createdTime" label="请求时间" min-width="170" /><el-table-column label="操作" width="100"><template #default="{ row }"><el-button text type="primary" :loading="approvingId === row.id" @click="approvePairing(row)">批准</el-button></template></el-table-column></el-table></el-card>
  </section>
</template>
<script setup lang="ts">
import { defineComponent, h, onMounted, reactive, ref, watch } from 'vue'
import { ElButton, ElMessage, ElMessageBox } from 'element-plus'
import { candidateProfileApi, pairingApi } from '../api'; import http from '../api/http'; import type { CandidateProfileResponse, ExtensionPairing, ProfileSnapshot } from '../types'
type Education = Record<string,string>; type Work = Record<string,string>; type Project = Record<string,string>
const uid = (prefix: string) => `${prefix}_${crypto.randomUUID()}`
const education = (): Education => ({ id:uid('edu'),school:'',degree:'',major:'',college:'',startDate:'',expectedGraduation:'',studyMode:'FULL_TIME',gpa:'' })
const internship = (): Work => ({ id:uid('work'),company:'',role:'',department:'',city:'',startDate:'',endDate:'',employmentType:'INTERNSHIP',industry:'',responsibilities:'',achievements:'',technologies:'' })
const project = (): Project => ({ id:uid('project'),name:'',role:'',startDate:'',endDate:'',type:'',teamSize:'',url:'',technologies:'',description:'',contributions:'' })
const SectionHeader = defineComponent({ props:{title:{type:String,required:true},hint:{type:String,required:true},editable:{type:Boolean,default:false}},emits:['add'],setup(props,{emit}){return()=>h('div',{class:'card-header'},[h('div',[h('span',props.title),h('small',props.hint)]),h(ElButton,{text:true,type:'primary',size:'small',disabled:!props.editable,onClick:()=>emit('add')},{default:()=>'+ 添加'})])} })
const ExperienceBlock = defineComponent({ props:{title:{type:String,required:true},summary:{type:String,default:''},editable:{type:Boolean,default:false}},emits:['remove'],setup(props,{emit,slots}){const expanded=ref(false);watch(()=>props.editable,value=>{if(!value)expanded.value=false});return()=>h('div',{class:'experience-block'},[h('div',{class:'experience-title'},[h('div',[h('strong',props.title),!props.editable&&h('small',{class:'experience-summary'},props.summary)]),h('div',{class:'experience-actions'},[h(ElButton,{text:true,type:'primary',size:'small',onClick:()=>expanded.value=!expanded.value},{default:()=>expanded.value||props.editable?'收起':'展开'}),props.editable&&h(ElButton,{text:true,type:'danger',size:'small',onClick:()=>emit('remove')},{default:()=> '删除'})])]),(props.editable||expanded.value)&&slots.default?.()])} })
const loading=ref(false),saving=ref(false),editing=ref(false),snapshots=ref<ProfileSnapshot[]>([]),pairingRequests=ref<ExtensionPairing[]>([]),approvingId=ref<number>(),serviceOnline=ref(false),runtimeLabel=ref('正在识别服务类型'); const profile=ref<CandidateProfileResponse>({profileId:'default',schemaVersion:'0.1',revision:0,content:{}}); const form=reactive({basic:{nameCn:'',gender:'UNSPECIFIED'},contact:{phone:'',email:'',currentCity:''},education:[] as Education[],work:[] as Work[],projects:[] as Project[]})
const clone = <T extends Record<string,string>>(factory:()=>T,item:any):T => ({...factory(),...item})
function bind(content:Record<string,any>){Object.assign(form.basic,{nameCn:content.basic?.nameCn||'',gender:content.basic?.gender||'UNSPECIFIED'});Object.assign(form.contact,{phone:content.contact?.phone||'',email:content.contact?.email||'',currentCity:content.contact?.currentCity||''});form.education=Array.isArray(content.education)?content.education.map((x:any)=>clone(education,x)):[];form.work=Array.isArray(content.work)?content.work.map((x:any)=>clone(internship,x)):[];form.projects=Array.isArray(content.projects)?content.projects.map((x:any)=>clone(project,x)):[]}
async function load(){loading.value=true;try{profile.value=await candidateProfileApi.get();bind(profile.value.content);snapshots.value=await candidateProfileApi.snapshots();pairingRequests.value=await pairingApi.pending();editing.value=false}finally{loading.value=false}}
const addEducation=()=>form.education.push(education()),removeEducation=(i:number)=>form.education.splice(i,1),addInternship=()=>form.work.push(internship()),removeInternship=(i:number)=>form.work.splice(i,1),addProject=()=>form.projects.push(project()),removeProject=(i:number)=>form.projects.splice(i,1)
function cancelEdit(){bind(profile.value.content);editing.value=false}
async function save(){if(form.education.some(x=>!x.school.trim())||form.work.some(x=>!x.company.trim())||form.projects.some(x=>!x.name.trim()))return ElMessage.warning('已添加的经历请填写必填名称');saving.value=true;try{const content={...profile.value.content,basic:{...form.basic},contact:{...form.contact},education:form.education.map(x=>({...x})),work:form.work.map(x=>({...x})),projects:form.projects.map(x=>({...x})),fieldMeta:profile.value.content.fieldMeta||{}};profile.value=await candidateProfileApi.save(content);bind(profile.value.content);snapshots.value=await candidateProfileApi.snapshots();editing.value=false;ElMessage.success(`档案已保存为修订 v${profile.value.revision}`)}finally{saving.value=false}}
async function restore(s:ProfileSnapshot){await ElMessageBox.confirm(`恢复 v${s.revision} 后会创建新的修订版本，是否继续？`,'恢复档案快照',{type:'warning'});profile.value=await candidateProfileApi.restore(s.id);bind(profile.value.content);snapshots.value=await candidateProfileApi.snapshots();ElMessage.success(`已恢复为新修订 v${profile.value.revision}`)}
async function approvePairing(r:ExtensionPairing){await ElMessageBox.confirm(`确认批准 Chrome 扩展“${r.displayName||r.extensionId}”吗？`,'批准扩展配对',{type:'warning'});approvingId.value=r.id;try{await pairingApi.approve(r.id);pairingRequests.value=await pairingApi.pending();ElMessage.success('配对已批准，请回到 Chrome 扩展完成令牌领取。')}finally{approvingId.value=undefined}}
onMounted(load);onMounted(async()=>{try{const health=await http.get('/applymate/v1/health')as{runtime?:string,dataStore?:string};runtimeLabel.value=health.runtime==='DESKTOP'?'桌面端（H2）':health.runtime==='WEB'?'Web 端（MySQL）':`未知服务（${health.dataStore||'未识别数据库'}）`;serviceOnline.value=true}catch{serviceOnline.value=false}})
</script>
<style>
.profile-page{display:grid;gap:14px;max-width:1240px}.page-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.page-heading h1{margin:3px 0 5px;font-size:26px}.page-heading p{margin:0;color:var(--el-text-color-secondary);line-height:1.55}.eyebrow{color:var(--el-color-primary)!important;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.profile-actions{display:flex;align-items:center;flex-wrap:wrap;justify-content:flex-end;gap:7px}.profile-form{display:grid;gap:14px}.form-card,.snapshot-card,.pairing-card{border-radius:12px}.card-header{display:flex;justify-content:space-between;align-items:center;gap:10px;font-weight:700}.card-header>div{display:flex;align-items:center;gap:8px}.card-header small{color:var(--el-text-color-secondary);font-weight:400}.compact-grid{display:grid;gap:0 12px}.compact-grid.four{grid-template-columns:repeat(4,minmax(0,1fr))}.compact-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.form-card .el-card__header{padding:10px 16px}.form-card .el-card__body{padding:13px 16px}.form-card .el-form-item{margin-bottom:10px}.form-card .el-form-item__label{font-size:12px}.experience-block{padding:10px 12px;border:1px solid var(--el-border-color-lighter);border-radius:9px;background:#fcfdff}.experience-block+.experience-block{margin-top:9px}.experience-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:7px;font-size:13px}.experience-title>div:first-child{display:flex;align-items:center;gap:10px}.experience-summary{color:var(--el-text-color-secondary);font-weight:400}.experience-actions{display:flex;align-items:center;gap:3px}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.detail-grid .el-form-item{margin-bottom:0}@media(max-width:900px){.compact-grid.four,.compact-grid.three{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.page-heading{display:grid}.profile-actions{justify-content:flex-start}.compact-grid.four,.compact-grid.three,.detail-grid{grid-template-columns:1fr}.card-header>div{display:grid;gap:2px}}
</style>
